# The Site Configuration

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ''
lang: en
title: s w a m p * d o n k e y
tagline: crime time
email: sw4mpd0nkey@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Another dumb vanity site with a collection of ctf write ups, tools, and oddities
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sw4mpd0nkey.github.io"
github_username:  sw4mpd0nkey

# Build settings
theme: minima
plugins:
  - jekyll-feed


github:
  username: sw4mpd0nkey             
twitter:
  username: sw4mpd0nkey            

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: sw4mpd0nkey
  email: mail@mail.me             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/sw4mpd0nkey      # change to your twitter homepage
    - https://github.com/sw4mpd0nkey       # change to your github homepage



# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: dark  # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/avatar.jpg
